// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, cloneRepository, config, express, pullRepository, validateHookSource;

  express = require('express');

  require('shelljs/global');

  app = express();

  app.use(express.json());

  app.use(express.urlencoded());

  app.set("port", process.env.PORT || 3000);

  config = {
    port: process.env.PORT || 1338,
    env: process.env.NODE_ENV || 'development'
  };

  validateHookSource = function(req, res, next) {
    var repo, _ref;
    try {
      repo = JSON.parse(req.body.payload).repository;
      if ((_ref = repo.name) !== 'vtexlab' && _ref !== 'docs' && _ref !== 'guide') {
        res.send(401, "Unauthorized");
      }
    } catch (_error) {
      res.send(401, "Unauthorized");
    }
    return next();
  };

  cloneRepository = function(req, res, next) {
    var repo;
    repo = JSON.parse(req.body.payload).repository;
    if (!test('-e', repo.name)) {
      return exec("git clone https://github.com/vtex/" + repo.name + ".git", function(code, output) {
        if (code !== 0) {
          res.send(500, output);
        }
        return next();
      });
    } else {
      return next();
    }
  };

  pullRepository = function(req, res, next) {
    var repo;
    repo = JSON.parse(req.body.payload).repository;
    return exec("cd " + repo.name + " && git fetch --all", function(code, output) {
      if (code !== 0) {
        res.send(500, output);
      }
      return exec("cd " + repo.name + " && git reset --hard origin/master", function(code, output) {
        if (code !== 0) {
          res.send(500, output);
        }
        return res.send(200, "Success.");
      });
    });
  };

  app.get('/', function(req, res) {
    return res.send("<h1>Works!</h1>");
  });

  app.post("/hooks", validateHookSource, cloneRepository, pullRepository);

  http.createServer(app).listen(app.get("port"), function() {
    console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
